ifeq ($(FF_PATH),)
        $(error variable FF_PATH is not set)
endif

ifeq ($(FF_DPDK),)
        FF_DPDK= $(FF_PATH)/dpdk/x86_64-native-linuxapp-gcc
endif

CC=       c++
OBJ=      ./obj
INCLUDE=  $(FF_PATH)/lib
CFLAGS=   -I$(INCLUDE)
DEBUG=    -g
FF_LIBS+= -L$(FF_PATH)/lib -L$(FF_DPDK)/lib -Wl,--whole-archive,-lfstack,--no-whole-archive
FF_LIBS+= -Wl,--whole-archive -lrte_pmd_vmxnet3_uio -lrte_pmd_i40e -lrte_pmd_ixgbe -lrte_pmd_e1000 -lrte_pmd_ring
FF_LIBS+= -Wl,--whole-archive -lrte_hash -lrte_kvargs -Wl,-lrte_mbuf -lethdev -lrte_eal -Wl,-lrte_mempool
FF_LIBS+= -lrte_ring -lrte_cmdline -lrte_cfgfile -lrte_kni -lrte_timer -Wl,-lrte_pmd_virtio
FF_LIBS+= -Wl,--no-whole-archive -lrt -lm -ldl -lcrypto -pthread

all:
	mkdir -p $(OBJ)
	make server
	make client

$(OBJ)/server.o: server/server.cpp
	$(CC) -c -o $@ $< $(CFLAGS) $(FF_LIBS) $(DEBUG)

$(OBJ)/client.o: client/client.cpp
	$(CC) -c -o $@ $< $(CFLAGS) $(FF_LIBS) $(DEBUG)

server: $(OBJ)/server.o
	$(CC) -o server_exe $(OBJ)/server.o $(CFLAGS) $(FF_LIBS) $(DEBUG)

client: $(OBJ)/client.o
	$(CC) -o client_exe $(OBJ)/client.o $(CFLAGS) $(FF_LIBS) $(DEBUG)

.PHONY: clean

clean:
	rm -f $(OBJ)/*
	rm -f server_exe client_exe
